### ISSUE TITLE
`Reserve` identifier not found

### ISSUE THREAD

**Issue by AKholetsky** [NoelFB/blah#1]
Windows 10. Visual Studio 2019.

An error appears when building a test project.

E:\Projects\CPP\blah\blah_source\public\blah\containers\list.h(103,3): error C3861: 'Reserve': identifier not found
E:\Projects\CPP\blah\blah_source\public\blah\containers\list.h(103,10): message : 'Reserve': function declaration must be available as none of the arguments depend on a template parameter

**Comment by NoelFB** [comment]
Thanks, fixed in merge!
