### ISSUE TITLE
PostProcessing

### ISSUE THREAD

**Issue by feresr** [NoelFB/blah#12]
Hi Noel 👋🏼 ! 
Thank you SO much for putting this together, along with the "how to make a game in SDL" video you have helped me tremendously to understand C++, OpenGL, and game programming. There's not a lot of content like yours out there, keep at it!

This is not really an 'issue' with the framework, I just want to ask you something regarding postprocessing using `blah`. 
Sorry if this is not the right place for this kind of question, I didn't know where else to ask, hope you don't mind. 
How did you implement a point-light system that you have in your game?

<img width="716" alt="Screen Shot 2021-11-25 at 10 48 39" src="https://user-images.githubusercontent.com/4985932/143453039-04c899aa-4553-49a0-a6e5-f4e164874a53.png">

How does postprocessing in general fit in the OpenGL abstraction in blah. Say I have a `PointLightComponent` how would that get rendered? 
Are you using another frame buffer, rendering the lights there as a grayscale image, and then compositing everything together?
if so, do you use two `Batch.cpp` objects? one for lights and one for everything else? 

I could not find a way of doing this in a clean way, I'm currently rendering all my lights after everything else got rendered and using a custom "light material" which is just a wrapper around a `Material`... but the code is a mess. Any pointers in the right direction would be greatly appreciated :) Have a great week

<img width="813" alt="Screen Shot 2021-11-25 at 11 00 51" src="https://user-images.githubusercontent.com/4985932/143454924-b04e0a4c-9e16-4c1a-8688-bfbc5898af3b.png">

**Comment by NoelFB** [comment]
Hey! Yeah generally what I end up doing is just draw stuff one-after-the-other, which is fine for my use cases. More modern rendering has command buffers that can often run these kinds of things in parallel.

For example, I just do something like:
```cpp
draw_gameplay(batcher);
batcher.render(target)
batcher.clear();
draw_lights(batcher);
batcher.render(target);
batcher.clear();
```

and then in each function I find the respective things I need to draw, use different materials, etc. In the case of my game I do actually draw the gameplay and lights to separate buffers. The code looks something like:
```cpp
// draw to respective buffers
draw_gameplay(gameplay_buffer, batcher);
draw_lights(light_buffer, batcher);

// now draw combined to the screen
batcher.tex(gameplay_buffer->attachment(0));
batcher.push_material(light_material);
batcher.tex(light_buffer->attachment(1));
batcher.pop_material();
batcher.render();
batcher.clear();
```

**Comment by feresr** [comment]
Thanks for hinting me in the right direction!

> Then in each function I find the respective things I need to draw

Curious to know how you do this... Do you have some kind of flag to know which things to render when iterating over the world? Something like this, maybe:

```cpp
enum FLAG { GAMEPLAY, LIGHTS }

draw_gameplay(gameplay_buffer, batcher) 
{
      world.render(batcher, GAMEPLAY) // render everything but lights
      batcher.render(gameplay_buffer);
}

draw_lights(light_buffer, batcher) 
{
      world.render(batcher, LIGHTS) // render only lights
      batcher.render(light_buffer);
}

class world {
      render(batcher, flag) {
            for (component : activeComponents) {
                  if (component.flags and flag) component->render(batcher);
            }
      }
}

```

In any case I think I can figure this out on my own. Thanks again for taking the time to reply to my previous message :)

**Comment by NoelFB** [comment]
No problem, hope it helps! And yeah, that's exactly right - I sort my game objects into different lists depending on what I need them for.
