### ISSUE TITLE
Mouse difference

### ISSUE THREAD

**Issue by SushilRagoonath** [NoelFB/blah#13]
Hi, I think it would be nice to have something like Input::mouse_diff() that gives the latest change to the mouse coordinates. I'm currently using something like this to move around my camera around world space but I think it could useful elsewhere.

**Comment by NoelFB** [comment]
Hey! My immediate feeling for this is just letting the user track the difference themselves, and keeping the amount of data blah tracks to a minimum. It seems pretty straight forward to just keep a `mouse_prev` value in your code, and calculate the diff each frame?

**Comment by SushilRagoonath** [comment]
Sounds good, was just wondering if this fit into blah
