### ISSUE TITLE
Vec3 / operation undefined

### ISSUE THREAD

**Issue by SushilRagoonath** [NoelFB/blah#14]
Mat4x4f::create_lookat is trying to normalize a Vec3. 
error C2676: binary '/': 'Blah::Vec3<float>' does not define this operator or a conversion to a type acceptable to the predefined operator
I did this in the 
template<class T>
	Vec3<T> Vec3<T>::normal() const {
		// return Vec3(x, y, z) / length();
		return Vec3(x / length(), y / length(), z / length()) ;
}

**Comment by NoelFB** [comment]
Thanks! should be fixed as of https://github.com/NoelFB/blah/commit/ae6a2f12d431d8b755ba0c9449d5d54771d044c0
