### ISSUE TITLE
Drop Platform abstraction in favor of SDL2

### ISSUE THREAD

**Issue by NoelFB** [NoelFB/blah#28]
Originally when I started this I wanted to have an abstraction layer for the platform implementation. However, SDL2 runs on everything I need for my use cases & I'm not interested in personally maintaining more platform abstraction layers, so I may simplify the API and just require SDL2.

**Comment by RobLoach** [comment]
If you're looking to keep the low-level and minimum dependencies, Sokol could be a good alternative https://github.com/floooh/sokol

**Comment by NoelFB** [comment]
Yeah I've seen (and used) Sokol and it's great! For the time being I'm still happy using my own rendering implementation(s) for the sake of learning, but long term I may switch to that.

**Comment by benjitrosch** [comment]
Are the goals for this:

1. deprecate win32 support (delete `blah_interal_platform_win32.cpp`, remove all `#ifdef`'s and the CMake flag)
2. replace the platform abstraction with just SDL2, AKA `blah_interal_platform_sdl2.cpp` just becomes `blah_internal_platform.cpp`

I wouldn't mind taking a stab at this unless you want to take it yourself!

**Comment by NoelFB** [comment]
Yeah this was my general idea ... I've been slightly hesitant to actually do it though due to console implementations. SDL supports most (all?) consoles I care about, but I also like the ability to write quick and dirty platform implementations without having to get the SDL-specific ports...

**Comment by benjitrosch** [comment]
That makes sense! It looks like the win32 platform and d3d11 renderer are pretty tightly coupled here? So maybe decoupling them is how you can start to phase out win32 from the rest of blah

**Comment by RandyGaul** [comment]
You can always implement the SDL2 functions you use on any new platform, if needed. That's another option. Personally that's what I'll do if needed. Just another thought.

**Comment by NoelFB** [comment]
> It looks like the win32 platform and d3d11 renderer are pretty tightly coupled here? So maybe decoupling them is how you can start to phase out win32 from the rest of blah

Hmm they shouldn't have any coupling at all! You can run the SDL backend with D3D11 - I do it right now on Windows.

> You can always implement the SDL2 functions you use on any new platform, if needed. That's another option. Personally that's what I'll do if needed. Just another thought.

Ohh that's a really good point! I'm not sure why I didn't consider that... That might be the best route to be honest.

**Comment by benjitrosch** [comment]
My mistake, my brain was confusing `BLAH_PLATFORM_WIN32` and `_WIN32` when reading the code 😅

**Comment by NoelFB** [comment]
Merged that in, seems like the right direction to me! I think eventually I'll remove the platform.cpp file entirely and just use SDL stuff inside the source files directly (ex. in `blah_app.cpp`)
