### ISSUE TITLE
Was upgrade to new SDL2 version difficult?

### ISSUE THREAD

**Issue by RandyGaul** [NoelFB/blah#29]
Just curious about what you had to change for the upgrade overall? The diff for your commit is really huge and a bit hard to read, so wanted to just ask here if that's ok!

**Comment by NoelFB** [comment]
Hmm I wonder if the line-endings changed or something, literally the only change I had was telling it to pull `2.26` instead of `2.24` so I'm unsure why it marked every line as changed.

**Comment by RandyGaul** [comment]
Might be line endings crlf and /n if you’re using two different editors
