### ISSUE TITLE
Direct graphics api usage

### ISSUE THREAD

**Issue by SushilRagoonath** [NoelFB/blah#30]
I'm looking to directly use directx11. Not sure if I should create a function somewhere in the app to get the ID3D11Device and ID3D11DeviceContext or maybe there is another way to obtain these but I'm not sure.

**Comment by NoelFB** [comment]
Right now there's no public API to access that... I could maybe have some way to expose this per-rendering API, although I'm not sure what the best way to do that would be right now.

Alternatively, depending on what you're trying to do, I could look into adding that API in general. There's a lot of missing features that I haven't really done (ex. depth buffers on the back buffer).

**Comment by SushilRagoonath** [comment]
I think adding the all the features I want would be quite cumbersome. I want to run some expirements with compute shaders
I also want to use the Dear ImGui win32 example, this requires the device and its context.
They don't seem like small framework features so I'll try hack in like this for now.
` //Under App::
void * get_d3d11_device();
void * get_d3d11_device_context();

// Under blah_renderer_d3d11.cpp

	void * App::get_d3d11_device() { return RENDERER->device; };
	void * App::get_d3d11_device_context() { return RENDERER->context; };
`

**Comment by NoelFB** [comment]
That makes sense! Probably best to leave that kind of thing in a fork for now, but I could see adding nicer hooks, especially for imgui!
